### PR TITLE
add prettier #2

### PR DESCRIPTION
**Pull request by itsmeAB**
Added prettier config.
Please review and suggest if anything wrong with the setup.

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Is it possible to incorporate airbnb coding style

**Comment by itsmeAB** [comment]
let me add

**Comment by itsmeAB** [comment]
@johnjacobkenny
Please review this
* Added eslint-config-airbnb-base and other eslint dev dependencies
* Added eslint config file - .eslintrc.json
* For now it is using all airbnb default code styling rules.
Please check and let me know if we need to turn off any rules.

**Comment by johnjacobkenny** [comment]
@itsmeAB I can see that you have added the npm script for running prettier. Do we need to use that, or does VS Code automatically pick up the eslint and prettier configs and run the code formatting on save? That is the ideal workflow imo.

**Comment by itsmeAB** [comment]
@johnjacobkenny  In editor options, we need to set true for formatOnSave. Otherwise, we can run `npm run prettier` or just simply do the document format. Not sure we can add something on this config for format on save.
Another idea maybe we can add husky for run lint check before the commit.

**Comment by johnjacobkenny** [comment]
@itsmeAB sounds good! Lets take those up once we feel there are inconsistencies

**Pull request merged**
